DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'dtd_app') THEN
    CREATE ROLE dtd_app LOGIN PASSWORD 'dtd_app_pw' NOSUPERUSER NOBYPASSRLS;
  END IF;
END
$$;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dtd_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dtd_app;
GRANT USAGE ON SCHEMA public TO dtd_app;
